version: '3'
networks:
  net:
    driver: bridge
services:
  internal-api-server:
    build: internal-api-server
    restart: always
    environment:
      - COOKIE=${COOKIE}
      - SECRET_KEY=${TIKTOK_API_SECRET}
      - INSTAGRAM_LOGIN=${INSTAGRAM_LOGIN}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD}
      - TWITTER_API_BEARER_SECRET=${TWITTER_API_BEARER_SECRET}
      - PORT=5000
    ports:
      - "5000:5000"
    expose:
      - 5000
    networks:
      - net
  tiktonick-bot:
    build: tiktonick-bot
    restart: always
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - TIKTOK_API_SECRET=${TIKTOK_API_SECRET}
      - TIKTOK_BOT_DATABASE_NAME=${TIKTONICK_DB_NAME}
      - TIKTOK_BOT_MONGO_CON_STRING=${TIKTONICK_MONGO_CON_STRING}
      - TIKTOK_URL=http://internal-api-server:5000/
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
    networks:
      - net