version: '3'
networks:
  net:
    driver: bridge
services:
  tiktok-api-server:
    build: tiktok-api-server
    restart: always
    environment:
      - COOKIE=${COOKIE}
      - SECRET_KEY=${TIKTOK_API_SECRET}
      - PORT=5000
    networks:
      - net
  tiktonick-bot:
    build: tiktonick-bot
    restart: always
    environment:
      - TELOXIDE_TOKEN=${TELOXIDE_TOKEN}
      - TIKTOK_API_SECRET=${TIKTOK_API_SECRET}
      - TIKTOK_BOT_DATABASE_NAME=${TIKTONICK_DB_NAME}
      - TIKTOK_BOT_MONGO_CON_STRING=${TIKTONICK_MONGO_CON_STRING}
      - TIKTOK_URL=http://tiktok-api-server:5000/
      - TWITTER_API_BEARER_SECRET=${TWITTER_API_BEARER_SECRET}
      - TWITTER_API_URL=https://api.twitter.com
    networks:
      - net