// This file is generated by generate_commands.py in. Generation date is 2022-04-09 20:27:04.984204
// The proper way to change commands is to edit commands_config directory and run the script.

use teloxide::utils::command::BotCommand;

#[derive(BotCommand, Clone)]
#[command(
    rename = "lowercase",
    description = "Supported commands for TikTok:",
    parse_with = "split"
)]
pub(super) enum TiktokCommands {
    #[command(
        rename = "ltiktok",
        description = "Send last liked tiktok video for given user"
    )]
    LastSub1(String),
    #[command(
        rename = "tiktok",
        description = "Send last posted tiktok video for given user"
    )]
    LastSub2(String),
    #[command(
        rename = "ltiktoks",
        description = "Send last n liked tiktok videos for given user"
    )]
    LastNSub1(String, u8),
    #[command(
        rename = "tiktoks",
        description = "Send last n posted tiktok videos for given user"
    )]
    LastNSub2(String, u8),
    #[command(
        rename = "sub_tiktok_likes",
        description = "Subscribe to receive notifications about new liked tiktok videos for given user"
    )]
    Subscribe1(String),
    #[command(
        rename = "sub_tiktok_videos",
        description = "Subscribe to receive notifications about new posted tiktok videos for given user"
    )]
    Subscribe2(String),
    #[command(
        rename = "unsub_tiktok_likes",
        description = "Unsubscribe from receiving notifications about new liked tiktok videos for given user"
    )]
    Unsubscribe1(String),
    #[command(
        rename = "unsub_tiktok_videos",
        description = "Unsubscribe from receiving notifications about new posted tiktok videos for given user"
    )]
    Unsubscribe2(String),
}

#[derive(BotCommand, Clone)]
#[command(
    rename = "lowercase",
    description = "Basic supported commands:",
    parse_with = "split"
)]
pub(super) enum BasicCommands {
    #[command(rename = "help", description = "Display this help message")]
    Help,
    #[command(
        rename = "subscriptions",
        description = "Display list of the subscription for this chat"
    )]
    Subscriptions,
}

#[derive(BotCommand, Clone)]
#[command(
    rename = "lowercase",
    description = "Supported commands for Instagram:",
    parse_with = "split"
)]
pub(super) enum InstagramCommands {
    #[command(
        rename = "last_story",
        description = "Send last Instagram story for given user"
    )]
    LastSub1(String),
    #[command(
        rename = "last_post",
        description = "Send last Instagram post for given user"
    )]
    LastSub2(String),
    #[command(
        rename = "last_stories",
        description = "Send last n Instagram stories for given user"
    )]
    LastNSub1(String, u8),
    #[command(
        rename = "last_posts",
        description = "Send last n Instagram posts for given user"
    )]
    LastNSub2(String, u8),
    #[command(
        rename = "subscribe_stories",
        description = "Subscribe to receive notifications about new stories for given user"
    )]
    Subscribe1(String),
    #[command(
        rename = "subscribe_posts",
        description = "Subscribe to receive notifications about new posts for given user"
    )]
    Subscribe2(String),
    #[command(
        rename = "unsubscribe_stories",
        description = "Unsubscribe from receiving notifications about new stories for given user"
    )]
    Unsubscribe1(String),
    #[command(
        rename = "unsubscribe_posts",
        description = "Unsubscribe from receiving notifications about new posts for given user"
    )]
    Unsubscribe2(String),
}

#[derive(BotCommand, Clone)]
#[command(
    rename = "lowercase",
    description = "Supported commands for Twitter:",
    parse_with = "split"
)]
pub(super) enum TwitterCommands {
    #[command(
        rename = "ltweet",
        description = "Send last liked tweet for given user"
    )]
    LastSub1(String),
    #[command(rename = "tweet", description = "Send last tweet for given user")]
    LastSub2(String),
    #[command(
        rename = "ltweets",
        description = "Send last n liked tweets for given user"
    )]
    LastNSub1(String, u8),
    #[command(rename = "tweets", description = "Send last n tweets for given user")]
    LastNSub2(String, u8),
    #[command(
        rename = "sub_twitter_likes",
        description = "Subscribe to receive notifications about new liked tweets for given user"
    )]
    Subscribe1(String),
    #[command(
        rename = "sub_tweets",
        description = "Subscribe to receive notifications about new tweets for given user"
    )]
    Subscribe2(String),
    #[command(
        rename = "unsub_twitter_likes",
        description = "Unsubscribe from receiving notifications about new liked tweets for given user"
    )]
    Unsubscribe1(String),
    #[command(
        rename = "unsub_tweets",
        description = "Unsubscribe from receiving notifications about new tweets for given user"
    )]
    Unsubscribe2(String),
}
